# Generated by Django 5.2 on 2025-05-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_educationentry_resumesummary_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='scraped_file',
            field=models.FileField(blank=True, null=True, upload_to='scraped_jobs'),
        ),
    ]
