# Generated by Django 5.2 on 2025-05-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_institutionprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionprofile',
            name='institution_name',
        ),
    ]
