# Generated by Django 5.2 on 2025-05-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='profile',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
