# Generated by Django 5.2 on 2025-05-13 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_jobapplication_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='profile',
            new_name='profile_data',
        ),
    ]
