# Generated by Django 5.2 on 2025-05-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_profile_jobapplication_profile_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='no_opening',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
