# Generated by Django 5.2 on 2025-05-20 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_jobpost_no_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.CreateModel(
            name='SavedApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobapplication')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.institutionprofile')),
            ],
            options={
                'unique_together': {('institution', 'application')},
            },
        ),
    ]
