# Generated by Django 5.2 on 2025-05-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_jobapplication_status_savedapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
