# Generated by Django 5.2 on 2025-05-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_jobpost_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='hire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
