# Generated by Django 5.2 on 2025-05-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_jobpost_hire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='hire_date',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='hire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
