# Generated by Django 5.2 on 2025-05-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_jobapplication_hire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
