# Generated by Django 5.2 on 2025-05-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_jobapplication_resume_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume_file',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_link',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
